### ISSUE TITLE
[UX] Bandwidth Friendly Hashing

### ISSUE THREAD

**Issue by arlateedaina** [A-Coom/coomer.party-scraper#10]
Problem is the name of the files. Files are already hashed, would only need switching from md5 to sha256 (which hashlib supports and conveniently it's a parameter)

- get user posts - `/{service}/user/{creator_id}`
- get user post - `/{service}/user/{creator_id}/post/{post_id}`

The filename is the hash. So from hexdigest(), building the path would be, `f"/{hex[0:2]}/{hex[2:4]}/{hex}.{extension}"` and they can be excluded.

-----

**Optimization on the above**

To not have to scan everything, get the latest file date. Then when getting user posts, everything up to that post can be removed.

-----

**Optimization on the current implementation** (lots of bandwidth could be saved)

right now it's downloading the full file, hashing it, then checking if it's not there to write. The server supports ranges. So we can request the first 100 bytes. 

Example, 

- `curl -r 0-100 https://n2.coomer.su/data/ab/ab/hash.mp4 | md5sum`
- then instead of hashing the full file locally, we can hash the start, 

```
with open("file_source.mp4", 'rb') as fd:
    chunk = fd.read(101)

start_hash = hashlib.md5(chunk).hexdigest()
```

**Comment by A-Coom** [comment]
Based on my own testing in the past, the suggestion you made is not reliable. The naming convention on the target servers has changed throughout time. I don't remember all past conventions, but the current model is based on the SHA256 hash of the file. Since this was not always the case, it cannot be reliably used to know if a file has been downloaded.

---

See #9 for the status of constraining downloading files based on date or other criteria.

---

Requesting only the first N bytes to test if a file has been downloaded is good in theory, but there are important considerations. For example, enough bytes need to be downloaded to make the comparison reliable (i.e. enough to skip the file header and get a decent way into the "meat" of the file). This is still preferable over downloading potentially several GB just to have it immediately discarded as a duplicate.

---

I am open to check pull requests addressing parts 2 and 3. You seem to know what you're talking about, so show me what you got :)

**Comment by A-Coom** [comment]
The dev branch has implemented many changes, including what was requested here. Looking for bug testers on these new features before building a release:
- Change in hashing to check for duplicates with a minimal download (part 3 of this issue).
- Complete change in usage (I recommend using the `--help`)
- Download posts in a range (including only a starting or ending offset)
- Download a single post.
- Download a single media.
- Streamed downloads, including the usage of a `.part` file while downloading.
- Switch to the `n` servers instead of the `c` servers for future-proofing.

**Comment by arlateedaina** [comment]
@A-Coom Got busy. I'll test what you have.

I was coming to add some info. My first pass, was skipping if already existed.
Was looking and noticed all file names I saw on the platform are actually the sha256 of the file.

```
diff --git a/scrape.py b/scrape.py
index 436ea04..b04d5f3
--- a/scrape.py
+++ b/scrape.py
@@ -1,6 +1,6 @@
 from scraping_utils.scraping_utils import compute_file_hashes, DownloadThread, multithread_download_urls_special, IMG_EXTS, VID_EXTS, TOO_MANY_REQUESTS, NOT_FOUND, THROTTLE_TIME
 from sys import stderr, stdout, argv
-from hashlib import md5
+from hashlib import sha256
 import requests
 import os
 import re
@@ -20,7 +20,7 @@ class CoomerThread(DownloadThread):
     F_TOKEN = 'A-Coom@github'
 
     # Initialize this CoomerThread
-    def __init__(self, file_name, url, dst, algo=md5, hashes={}):
+    def __init__(self, file_name, url, dst, algo=sha256, hashes={}):
         DownloadThread.__init__(self, file_name, url, dst, algo, hashes)
         self.base = url
         self.server = 1
@@ -36,12 +36,20 @@ class CoomerThread(DownloadThread):
         self.server = self.server + 1
         if(self.server > self.C_SERVER_COUNT): self.server = 1
 
+    def already_exists(self, url_hash):
+        return url_hash in self.hashes.keys()
+
     # Perform downloading until successful, switching coom servers as "too many requests" responses are received
     def run(self):
         ext = self.base.split('.')[-1]
         name = self.base.split('/')[-1].split('.')[0]
         media = None
 
+        if self.already_exists(name):
+            # Already exists, setting to finished and exiting early
+            self.status = self.FINISHED
+            return
+
         try:
             while(self.status == self.STANDBY):
                 self.status = self.DOWNLOADING
@@ -108,19 +116,20 @@ def download_media(urls, include_imgs, include_vids, dst):
 
     if(include_imgs):
         if(os.path.isdir(pics_dst)):
-            hashes = compute_file_hashes(pics_dst, IMG_EXTS, md5, hashes)
+            hashes = compute_file_hashes(pics_dst, IMG_EXTS, sha256, hashes)
         else:
             os.mkdir(pics_dst)
 
     if(include_vids):
         if(os.path.isdir(vids_dst)):
-            hashes = compute_file_hashes(vids_dst, VID_EXTS, md5, hashes)
+            hashes = compute_file_hashes(vids_dst, VID_EXTS, sha256, hashes)
         else:
             os.mkdir(vids_dst)
 
     stdout.write('\n')
 
-    hashes = multithread_download_urls_special(CoomerThread, urls, pics_dst, vids_dst, algo=md5, hashes=hashes)
+
+    hashes = multithread_download_urls_special(CoomerThread, urls, pics_dst, vids_dst, algo=sha256, hashes=hashes)
     return len(hashes)
 
```
 
Documenting this since it helped me debug, I added this to be able to step through via the debugger,

```
diff --git a/scraping_utils.py b/scraping_utils.py
index 8197141..4bce195 100644
--- a/scraping_utils.py
+++ b/scraping_utils.py
@@ -210,7 +210,22 @@ def multithread_download_urls_special(Dtsc, urls, pics_dst, vids_dst, algo=hashl
     # Confirm that Dtsc is a subclass of DownloadThread (or the same class)
     if(not issubclass(Dtsc, DownloadThread)):
         return hashes
-        
+
+    DEBUG = True
+    if DEBUG:
+        # Non-threaded mode for debugging
+        stdout.write("[DEBUG MODE] Running in non-threaded mode.\n")
+        for name in sorted(urls.keys(), reverse=True):
+            url = urls[name]
+            ext = url.split('.')[-1]
+            dst = pics_dst if ext in IMG_EXTS else vids_dst
+            # Simulate the run method for debugging
+            thread = Dtsc(name, url, dst, algo=algo, hashes=hashes)
+            thread.run()  # Directly call run instead of start
+            thread.print_status()
+        return hashes
+
+
     # Print the initial status box
     msg = f'Successfully downloaded media from 0/{len(urls)} URLs'
     print(f'.{"="*(len(msg)+2)}.')
```

**Comment by A-Coom** [comment]
> I was coming to add some info. My first pass, was skipping if already existed. Was looking and noticed all file names I saw on the platform are actually the sha256 of the file.

After looking again, I realize I made a mistake. You are correct, the names of the server are the SHA-256 hash. Thank you for bringing that to my attention!

The dev branch now implements a parameter to use this method of duplicate detection. In general, those with very limited bandwidth will benefit from using `--full-hash`. But it does require more computing power, especially for large files. If you are happy with the implementation, this issue will be closed.

The servers have been finicky recently, so I have not been able to test very thoroughly. There will hopefully be a release before the end of the month if the servers don't get nuked.
