### ISSUE TITLE
[UX] Target Specific Posts

### ISSUE THREAD

**Issue by emptyLIMBOempty** [A-Coom/coomer.party-scraper#9]
implementing an argument in prompt for the user to enter the starting/ending numbers or range of posts?, ensuring they are valid before proceeding.
This will help when the user doesn't need to scrape the whole profile!

**Comment by A-Coom** [comment]
This is not off the table, but will require a substantial amount of change in the usage and I would want to do it right.

I would want to change the usage to be flag based instead of positional first. Then flags for range of posts can be implemented, either by post index or post date.

This would also be a good opportunity to to add support for downloading a single post instead of a profile.

ETA... much later. Unfortunately, life is not allowing me to focus on a coomer project for some time. I'm open to reviewing any pull requests that implement this.

**Comment by A-Coom** [comment]
Further testing has not shown any bugs with the solution to this issue.
